baseURL = "https://davidkarlsson.tech/"
languageCode = "en-us"
title = "David Karlsson"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
email = "davidkarlsson0@gmail.com"
phone = "+4673-682-35-47"